spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/fubanko-db
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5434/fubanko-db
    user: admin
    password: 123
