spring:
  application:
    name: fubanko

  datasource:
    url: jdbc:postgresql://localhost:5434/fubanko-db
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
