spring:
  application:
    name: fubanko

  datasource:
    url: jdbc:postgresql://localhost:5434/fubanko-db
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5434/fubanko-db
    user: admin
    password: 123


jwt:
  security:
    private-key: classpath:app.key
    public-key: classpath:app.pub
