
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: fubanko-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"

volumes:
  postgres_data:
